# py3.7/travis: https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
language: node_js
node_js:
  - "8"
dist: xenial
sudo: true
services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    update: true
    packages:
      - libsnappy-dev
      - libunwind-dev
      - make
      - python3-pip

before_install:
  - sudo pip3 install -U scons boto taschenmesser

before_script:
  - docker run -d -v $PWD/.crossbar:/node/config -p 8080:8080 crossbario/crossbar --config /node/config/config.json

script:
  - nodeunit test/test_connect.js
  - nodeunit test/test_serialization_cbor.js
  - nodeunit test/test_pubsub_multiple_matching_subs.js
  - npm test
