# py3.7/travis: https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
language: node_js
node_js:
  - "8"
dist: xenial
sudo: true

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    update: true
    packages:
      - libsnappy-dev
      - libunwind-dev
      - make
      - python3-pip

before_install:
  - pip install -U scons boto taschenmesser
