# py3.7/travis: https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
language: node_js
node_js:
  - "8"
dist: xenial
sudo: true
services:
  - docker

addons:
  apt:
    update: true
    packages:
      - python3-pip

before_install:
  - sudo pip3 install --no-cache-dir -U scons boto taschenmesser

before_script:
  - docker run -d -v $PWD/.crossbar:/node/config -p 8080:8080 crossbario/crossbar --config /node/config/config.json
  - sleep 5
